### PR TITLE
Update sampleJava.java

### PR DESCRIPTION
**Pull request by WaddupBoi**
SAMPLE TEXT (mehoy minoy hiyoy menoy)

### CODE REVIEW

**Comment by trxxxx** [comment]
:)

**Comment by ddiing** [comment]
edi shingggg

**Comment by Kimlouiemartinez** [comment]
Yay!

**Comment by cleariejoydenosta** [comment]
sssshhhh

**Comment by JhoannaOlisco** [comment]
Huwaaaaw

**Comment by Brukoto123** [comment]
:)

**Comment by jeriemiebolido** [comment]
amazing.. i was so impressed!!

**Comment by louisedelid** [comment]
o sht here come dat boiiiii

**Comment by Brukoto123** [comment]
edi wow :)

**Comment by Kimlouiemartinez** [comment]
what are those!!

**Comment by JhoannaOlisco** [comment]
Malamig!!

**Comment by jeriemiebolido** [comment]
cf to cf?

**Comment by Brukoto123** [comment]
GSW VS CAVS

**Comment by trxxxx** [comment]
Like Back

**Comment by trxxxx** [comment]
PUSUAN NIYO DP KO

**Comment by Suhochachi** [comment]
LIKE BACK PO

**Comment by JhoannaOlisco** [comment]
RT ko dp mo?

**Comment by ShairaAnneElesio** [comment]
HAHA :D

**Comment by Kimlouiemartinez** [comment]
Pa FS po

**Comment by jeriemiebolido** [comment]
pki like nmn po tung post ko ;)))) floodlikes ko ikw hahhahhahhha

**Comment by Brukoto123** [comment]
Magbago na kyo si dU30 na ang Presidente :)

**Pull request merged**
